# Jekyll configuration for GitHub Pages with Architect theme
remote_theme: pages-themes/architect@v0.2.0
title: anas_builds
description: >- 
     My Lab to try and learn new things
     and share my projects with the world.
  
baseurl: "/anas_builds.github.io"
url: "https://abracadabracools.github.io"
plugins:
  - jekyll-remote-theme
